---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: dockerhub
  namespace: flux-system
spec:
  image: guybalmas/example-app
  interval: 1m0s
#  secretRef:
#    name: docker-registry-credentials