---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: dockerhub
  filterTags:
    pattern: '^b(\d)+\.(\d)+\.(\d)+'
  policy:
    alphabetical:
      order: asc
#  policy:
#    semver:
#      range: 'x.x.x'
#
