apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: my-image
  namespace: default
spec:
  tag: guybalmas/example-app:2.0.0
  serviceAccountName: kpack-service-account
  builder:
    kind: ClusterBuilder
    name: my-cluster-builder
  source:
    git:
      revision: main
      url: https://github.com/guybalmas/example-app
  build:
    env:
      - name: "BPL_JAVA_NMT_ENABLED"
        value: "false"
      - name: "BP_JVM_TYPE"
        value: "JRE"
      - name: "BP_JVM_VERSION"
        value: "11"
      - name: "BP_OCI_AUTHORS"
        value: "GuyBalmas"
      - name: "BP_OCI_TITLE"
        value: "example-app"
#      - name: "BP_OCI_VERSION"
#        value: "1.0.0"