apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: default
secrets:
  - name: docker-registry-credentials
  - name: docker-registry-credentials-v2
imagePullSecrets:
  - name: docker-registry-credentials
  - name: docker-registry-credentials-v2