apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default-cluster-store
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java
#  serviceAccountRef:
#    name: kpack-service-account
#    namespace: default