---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: dockerhub
  policy:
    semver:
      range: 'x.x.x'

