apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: example-app-chart
      version: ">=3.0.0"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
  values:
    image: guybalmas/example-app:b1.20220717.034631 # {"$imagepolicy": "flux-system:example-app"}